# Generated by Django 5.2.14 on 2026-05-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('label', models.CharField(max_length=160)),
                ('value', models.CharField(max_length=80)),
                ('evolution', models.CharField(blank=True, max_length=40)),
                ('impact', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Fort'), ('critical', 'Critique')], default='medium', max_length=16)),
                ('tone', models.CharField(choices=[('neutral', 'Neutre'), ('gold', 'Important'), ('green', 'Positif'), ('red', 'A surveiller')], default='neutral', max_length=16)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['label'],
                'indexes': [models.Index(fields=['label'], name='analytics_s_label_b56bd1_idx'), models.Index(fields=['impact'], name='analytics_s_impact_e93574_idx'), models.Index(fields=['tone'], name='analytics_s_tone_76d74a_idx')],
            },
        ),
    ]
