services:
  - type: web
    name: couture-api
    runtime: python
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DEBUG
        value: "False"
  - type: web
    name: couture-web
    runtime: node
    rootDir: frontend
    buildCommand: npm ci && npm run build
    startCommand: npx next start -H 0.0.0.0 -p $PORT
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://couture-api.onrender.com/api/v1
