# Generated by Django 5.2.14 on 2026-05-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('order_late', 'Commande retardee'), ('appointment', 'Rendez-vous'), ('payment', 'Paiement'), ('delivery', 'Livraison'), ('manual', 'Manuelle')], default='manual', max_length=32)),
                ('channel', models.CharField(choices=[('web', 'Web'), ('android_tailor', 'Android tailleur'), ('android_client', 'Android client'), ('whatsapp', 'WhatsApp futur')], default='web', max_length=32)),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('normal', 'Normale'), ('high', 'Haute'), ('urgent', 'Urgente')], default='normal', max_length=16)),
                ('status', models.CharField(choices=[('unread', 'Non lue'), ('read', 'Lue'), ('archived', 'Archivee')], default='unread', max_length=16)),
                ('target_url', models.CharField(blank=True, max_length=240)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'), models.Index(fields=['priority'], name='notificatio_priorit_bf8ea0_idx'), models.Index(fields=['status'], name='notificatio_status_d92267_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
