# Generated by Django 5.2.14 on 2026-05-13 09:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('tailors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('appointment_type', models.CharField(choices=[('fitting', 'Essayage'), ('delivery', 'Livraison'), ('consultation', 'Consultation'), ('urgent', 'Urgence')], default='consultation', max_length=24)),
                ('priority', models.CharField(choices=[('normal', 'Normale'), ('high', 'Haute'), ('urgent', 'Urgente')], default='normal', max_length=16)),
                ('status', models.CharField(choices=[('scheduled', 'Programme'), ('confirmed', 'Confirme'), ('completed', 'Termine'), ('cancelled', 'Annule'), ('missed', 'Manque')], default='scheduled', max_length=16)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clients.client')),
                ('tailor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='tailors.tailorprofile')),
            ],
            options={
                'ordering': ['start_at', '-created_at'],
                'indexes': [models.Index(fields=['start_at'], name='appointment_start_a_c0d05a_idx'), models.Index(fields=['appointment_type'], name='appointment_appoint_3d8254_idx'), models.Index(fields=['priority'], name='appointment_priorit_cb5826_idx'), models.Index(fields=['status'], name='appointment_status_8fe9d7_idx')],
            },
        ),
    ]
