# Generated by Django 5.2.14 on 2026-05-12 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('label', models.CharField(default='Profil principal', max_length=120)),
                ('category', models.CharField(choices=[('man', 'Homme'), ('woman', 'Femme'), ('child', 'Enfant')], max_length=16)),
                ('unit', models.CharField(default='cm', max_length=8)),
                ('measurements', models.JSONField(default=dict)),
                ('reference_photos', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_profiles', to='clients.client')),
            ],
            options={
                'ordering': ['client__full_name', '-is_default', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MeasurementRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_measurements', models.JSONField(default=dict)),
                ('new_measurements', models.JSONField(default=dict)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='measurements.measurementprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
