# Generated by Django 5.2.14 on 2026-05-12 11:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('measurements', '0001_initial'),
        ('tailors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('bazin', 'Bazin'), ('costume', 'Costume'), ('robe', 'Robe'), ('kaftan', 'Kaftan'), ('boubou', 'Boubou'), ('uniforme', 'Uniforme'), ('mariage', 'Mariage'), ('luxe', 'Luxe'), ('casual', 'Casual'), ('africain_moderne', 'Africain moderne')], max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to='patterns/')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('trend_score', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=32, unique=True)),
                ('fabric', models.CharField(blank=True, max_length=140)),
                ('color', models.CharField(blank=True, max_length=80)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('advance_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit_date', models.DateField(default=django.utils.timezone.localdate)),
                ('delivery_date', models.DateField()),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('normal', 'Normale'), ('high', 'Haute'), ('urgent', 'Urgente')], default='normal', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('cutting', 'Decoupe'), ('sewing', 'Couture'), ('finishing', 'Finition'), ('ready', 'Pret'), ('delivered', 'Livre'), ('late', 'Retard'), ('cancelled', 'Annule')], default='pending', max_length=24)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('assigned_tailor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='tailors.tailorprofile')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='clients.client')),
                ('measurement_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='measurements.measurementprofile')),
                ('pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.pattern')),
            ],
            options={
                'ordering': ['delivery_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=24)),
                ('actor', models.CharField(blank=True, max_length=120)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['code'], name='orders_orde_code_77e86c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['delivery_date'], name='orders_orde_deliver_e4274f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['priority'], name='orders_orde_priorit_b622f0_idx'),
        ),
    ]
