# Generated by Django 5.2.14 on 2026-05-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=160)),
                ('phone', models.CharField(db_index=True, max_length=40)),
                ('whatsapp', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('gender', models.CharField(choices=[('male', 'Homme'), ('female', 'Femme'), ('child', 'Enfant'), ('other', 'Autre')], default='other', max_length=16)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('favorite_sizes', models.JSONField(blank=True, default=dict)),
                ('private_notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='clients/')),
                ('vip_level', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['full_name'], name='clients_cli_full_na_193c54_idx'), models.Index(fields=['phone'], name='clients_cli_phone_164f4c_idx'), models.Index(fields=['vip_level'], name='clients_cli_vip_lev_cc46b0_idx')],
            },
        ),
    ]
