# Generated by Django 5.2.14 on 2026-05-13 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('core', '0002_workshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='core.workshop'),
        ),
    ]
