# Generated by Django 5.2.14 on 2026-05-12 11:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('label', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('fabric', 'Tissu'), ('salary', 'Salaire'), ('rent', 'Loyer'), ('equipment', 'Materiel'), ('transport', 'Transport'), ('other', 'Autre')], default='other', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('spent_at', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-spent_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('cash', 'Especes'), ('mobile_money', 'Mobile money'), ('card', 'Carte'), ('transfer', 'Virement'), ('other', 'Autre')], default='cash', max_length=24)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Paye'), ('cancelled', 'Annule'), ('refunded', 'Rembourse')], default='paid', max_length=24)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='clients.client')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='orders.order')),
            ],
            options={
                'ordering': ['-paid_at', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'), models.Index(fields=['paid_at'], name='payments_pa_paid_at_b40014_idx'), models.Index(fields=['method'], name='payments_pa_method_70cfb8_idx')],
            },
        ),
    ]
