# Generated by Django 5.2.14 on 2026-05-12 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TailorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=160)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('specialty', models.CharField(blank=True, max_length=120)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('busy', 'Charge'), ('offline', 'Absent')], default='available', max_length=24)),
                ('quality_score', models.DecimalField(decimal_places=2, default=4.5, max_digits=4)),
                ('average_delay_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tailor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
